//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthFinderAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Specialty { get; set; }
        public Nullable<short> Rating { get; set; }
        public string Location { get; set; }
        public string Languages { get; set; }
    }
}
